//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MoltenMotelLib
{
    public enum eGameSpeed
    {
        SLOW = 5000,
        MEDIUM = 3000,
        FAST = 1000,
        TEST = 1,
    }
}