//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MoltenMotelLib
{
    public enum eRoomTemp
    {
        SAFE = 0,
        DANGER = 150,
        SMOULDER = 300,
        FIRE = 600,
        BURNEDOUT = 700,
    }
}