//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MoltenMotelLib
{

    class Game
    {
        Motel motel;
        public int RefreshRate;
        Parser parser;

        public Game()
        {
            RefreshRate = (int)eGameSpeed.MEDIUM;
            parser = new Parser();
            motel = new Motel(16);
        }

        public void gameStart()
        {
            HandlingInput hi = new HandlingInput(motel);
            printIntro();
            hi.play();
            printOutro();
        }

        public void printIntro() {
            //Console.WriteLine("Sorry we have no rooms available at the Molten Motel.\nWell, they are available, we just need \nsomeone to put out the fire.\nYou do it. Thanks, Love Mr. Manager.");
            //Console.WriteLine("");
            Console.WriteLine("Welcome to the Molten Motel!\n\nType help for a list of commands.\n\nPut out all the fires to win.");

        }

        public void printOutro()
        {
            Console.WriteLine("BYE!");
        }

        public void tickTock(Object data)
        {
            if (!motel.gameOver) {
                motel.tickTock();
            }
        }

    }

}