//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MoltenMotelLib {
  public class Truck {
        public int truckID;
        public eFiretruckStatus truckStatus { get; set; }
        public int coolant { get; set; }

        public Truck() { truckStatus = eFiretruckStatus.FREE;
        coolant = 600;
        }
        
        public Boolean goToRoom(int rID) {
            //if status is oncall return
            //if coolant is more than 0 
                //put out fire
                //if fire is out set free
                //else need more coolant set free
            if (truckStatus != eFiretruckStatus.FREE) {
                Console.WriteLine("You cant do that unless the truck is FREE.");
                return false;
            }if(coolant <= 0){
                Console.WriteLine("Fill up truck.");
                
                return false;
            }
            truckStatus = eFiretruckStatus.ONCALL;
            return true;
                
           
        }

        public void tick() {
            if (truckStatus == eFiretruckStatus.ONCALL && coolant > 0) {
                coolant -= 40;
                Console.WriteLine("Your coolant level is " + coolant);
            }
            if (coolant <= 0) {
                Console.WriteLine("You are out of coolant, you need to recall.");
            }
        }


        public void recall() {
            if (truckStatus != eFiretruckStatus.ONCALL) {
                Console.WriteLine("You cant do that unless the truck is ONCALL.");
                return;
            } else {
                truckStatus = eFiretruckStatus.STATIONED;
            }

        }
        public void refill() { 
            if (truckStatus != eFiretruckStatus.STATIONED) {
                Console.WriteLine("You cant do that unless the truck is STATIONED.");
                return;
            }else{
                coolant = 600;
                Console.WriteLine("Your truck has 600 coolant.");
                truckStatus = eFiretruckStatus.FREE;
            }
        }
        public void report() {
            Console.WriteLine("The Engine " + truckID + " has " + coolant + " litres and is currently " + truckStatus);
        }
        public void report(eRoomTemp roomStatus) {
            Console.WriteLine("The Engine " + truckID + " has " + coolant + " litres and is currently " + truckStatus + " the room is " + roomStatus);
        }
        
    }

}